name: Deploy Serverless AWS

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.repository == 'redwoodjs/deploy-target-ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required because lerna uses tags to determine the version.
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      ## This method doesn't work with Yarn v1
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      # - name: Cache yarn
      #   uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: yarn-${{ hashFiles('yarn.lock') }}
      #     restore-keys: |
      #       yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
        working-directory: ./serverless-aws

      # - name: Build
      #   run: yarn build

      - name: Deploy
        run: |
          yarn rw deploy serverless
